version: 2
jobs:
  build:
    docker:
      - image: pandoc/latex

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command:
            apk add make texlive-xetex

      - run:
          name: Export recipes to consolidated markdown
          command:
            ./generate_book.sh markdown

      - run:
          name: Export recipes to consolidated pdf
          command:
            ./generate_book.sh pdf

      - run:
          name: Check if markdown exists
          command:
            test -s recipe_book.md

      - run:
          name: Check if pdf exists
          command:
            test -s recipe_book.pdf
